version: '3'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:sechung
    restart: always
    volumes: 
      - database:/var/lib/mysql
    networks: 
      - inception
    env_file: 
      - .env
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress    
    image: wordpress:sechung
    restart: always
    volumes:
      - website:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    depends_on:
      - mariadb
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:sechung
    restart: always
    ports:
      - 443:443
    volumes:
      - website:/var/www/html
    networks: 
      - inception
    env_file:
      - .env
    depends_on:
      - wordpress

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/database
      o: bind
  website:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/website
      o: bind
networks:
  inception:
    driver: bridge
